title: "Mon Portfolio"
theme: jekyll-theme-cayman
markdown: kramdown
kramdown:
  math_engine: mathjax

header_pages:
  - index.md
  - cours.md
  - articles.md
  - travaux.md

sass:
  style: compressed
